apiVersion: apps/v1
kind: Deployment
metadata:
  name: maps
  labels:
    app.kubernetes.io/part-of: navigatum
    app.kubernetes.io/name: maps
  namespace: {{ $.Values.namespace }}
spec:
  replicas: {{ if eq "nav.tum.de" $.Values.url }}2{{ else }}1{{ end }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/part-of: navigatum
      app.kubernetes.io/name: maps
  strategy:
    rollingUpdate:
      maxSurge: {{ if eq "nav.tum.de" $.Values.url }}50%{{ else }}100%{{ end }}
      maxUnavailable: {{ if eq "nav.tum.de" $.Values.url }}50%{{ else }}0%{{ end }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: navigatum
        app.kubernetes.io/name: maps
    spec:
      priorityClassName: {{ $.Values.url }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tileserver
                operator: In
                values:
                - ready
      volumes:
        - name: tmp-tileserver
          emptyDir: {}
        - name: sprites-tileserver
          emptyDir: {}
        - name: tileserver-vol
          persistentVolumeClaim:
            readOnly: false
            claimName: tileserver-pvc
        - name: tileserver-config
          configMap:
            name: tileserver-config
      initContainers:
        - name: tileserver-init-sprites
          image: "busybox:latest"
          command:
          - sh
          - -c
          {{- $spritesURL := "https://raw.githubusercontent.com/maputnik/osm-liberty/gh-pages/sprites" }}
          - "rm -f /sprites/* && wget -P /sprites {{ $spritesURL }}/osm-liberty.json {{ $spritesURL }}/osm-liberty@2x.json {{ $spritesURL }}/osm-liberty.png {{ $spritesURL }}/osm-liberty@2x.png"
          volumeMounts:
            - mountPath: /sprites
              name: sprites-tileserver
      containers:
        - name: tileserver
          image: maptiler/tileserver-gl:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: tileserver
          args:
            - --public_url=https://{{ $.Values.url }}/maps/ # we want this to live under /maps/
          volumeMounts:
            - name: tmp-tileserver
              mountPath: /tmp
            - name: tileserver-vol
              mountPath: /data
            - name: tileserver-config
              mountPath: /data/config.json
              subPath: config.json
            - name: sprites-tileserver
              mountPath: /data/sprites
            - name: tileserver-config
              mountPath: /data/styles/osm-liberty.json
              subPath: osm-liberty.json
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
              - ALL
          resources:
            requests:
              cpu: {{ if eq "nav.tum.de" $.Values.url }}100m{{ else }}10m{{ end }}
              memory: {{ if eq "nav.tum.de" $.Values.url }}800Mi{{ else }}300Mi{{ end }}
            limits:
              memory: {{ if eq "nav.tum.de" $.Values.url }}1000Mi{{ else }}500Mi{{ end }}
          livenessProbe:
            httpGet:
              path: /health
              port: tileserver
            failureThreshold: 2
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /health
              port: tileserver
            failureThreshold: 6
            periodSeconds: 10
        - name: tileserver-src # serve tileserver-vol  at /maps/vol/...
          image: alpine:18
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 873
              name: rsync
          volumeMounts:
            - name: tileserver-vol
              mountPath: /home/maps/vol
              readOnly: true
            - name: tileserver-config
              mountPath: /etc/rsyncd.conf
              subPath: rsyncd.conf
