apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  labels:
    app.kubernetes.io/part-of: navigatum
  namespace: {{ $.Values.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ $.Values.url }}`) && PathPrefix(`/api/`)
      services:
        - name: api-svc
          port: 3003
    - kind: Rule
      match: Host(`{{ $.Values.url }}`) && PathPrefix(`/maps/vol/`)
      services:
        - name: maps-svc
          port: 7771
    - kind: Rule
      match: Host(`{{ $.Values.url }}`) && PathPrefix(`/maps/`)
      services:
        - name: maps-svc
          port: 8080
      middlewares:
        - name: stripprefix
        - name: compress
        - name: cache-2-months
    - kind: Rule
      match: Host(`{{ $.Values.url }}`) && PathPrefix(`/cdn/`)
      services:
        - name: cdn-svc
          port: 3002
      middlewares:
        - name: stripprefix
    - kind: Rule
      match: Host(`{{ $.Values.url }}`)
      services:
        - name: webclient-svc
          port: 3000
    - kind: Rule
      match: Host(`nav.tum.sexy`) || Host(`www.nav.tum.de`)
      services:
        - name: noop@internal
          kind: TraefikService
      middlewares:
        - name: nav-tum-de-redirect
  tls:
    secretName: {{ $.Values.url }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-http
  labels:
    app.kubernetes.io/part-of: navigatum
  namespace: {{ $.Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ $.Values.url }}`)
      services:
        - name: noop@internal
          kind: TraefikService
      middlewares:
        - name: https
    - kind: Rule
      match: Host(`nav.tum.sexy`) || Host(`www.nav.tum.de`)
      services:
        - name: noop@internal
          kind: TraefikService
      middlewares:
        - name: nav-tum-de-redirect
