name: Update data from upstream

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-dataupdate
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 2 * * 2"
  workflow_dispatch:
permissions: {}

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: {persist-credentials: false}
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10.14.0
          package_json_file: webclient/package.json
          run_install: |
            - cwd: webclient
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, openapi-format]
      - name: Setup Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: '3.14'
      - name: Install python dependencies
        run: pip install -r data/requirements.txt -r requirements-dev.txt
      - run: rm *tumonline.csv
        working-directory: data/external/results/
      - name: Download tumonline data
        continue-on-error: true # a PR deleting all data will be created if this fails => fail obvious
        run: PYTHONPATH=$PYTHONPATH:.. python3 scrapers/tumonline.py
        env:
          CONNECTUM_OAUTH_CLIENT_ID: "${{ secrets.CONECTUM_OAUTH_CLIENT_ID }}"
          CONNECTUM_OAUTH_CLIENT_SECRET: "${{ secrets.CONECTUM_OAUTH_CLIENT_SECRET }}"
        working-directory: data/external
      - continue-on-error: true # a PR deleting all data will be created if this fails => fail obvious
        run: ls -lah data/external/results
      - continue-on-error: true # a PR deleting all data will be created if this fails => fail obvious
        run: du -sh data/external/results/*
      - name: Fix linting errors
        continue-on-error: true
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          add-paths: data/external/results
          commit-message: Synced the data with upstream
          title: "chore(data): Synced the data with upstream datasources"
          body: |
            PR comes from [this Workflow Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            - Updated the data with upstream sources
            - Auto-generated by [create-pull-request][1]
            
            [ 1 ]: https://github.com/peter-evans/create-pull-request
          assignees: CommanderStorm
          branch: chore/data-update
          delete-branch: true
